name: Run Unit Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Assuming pytest is used for unit testing

      - name: Run Unit Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Adjust pytest arguments as needed
